name: afia_plus_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_svg: ^2.2.1
  get_it: ^9.2.0
  intl: ^0.20.2
  lucide_flutter: ^0.552.0
  path: ^1.9.1
  shared_preferences: ^2.5.3
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.3.6
  file_picker: ^8.1.4
  image_picker: ^1.2.1
  path_provider: ^2.1.4
  open_filex: ^4.7.0
  url_launcher: ^6.3.1
  firebase_core: ^4.2.1
  firebase_messaging: ^16.0.4
  flutter_local_notifications: ^19.5.0
  http: ^1.6.0
  app_links: ^7.0.0
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/prescription pdfs/
  fonts:
    - family: Syne
      fonts:
        - asset: assets/fonts/Syne-Regular.ttf
          weight: 400
        - asset: assets/fonts/Syne-Medium.ttf
          weight: 500
        - asset: assets/fonts/Syne-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Syne-Bold.ttf
          weight: 700
        - asset: assets/fonts/Syne-ExtraBold.ttf
          weight: 800