name: afia_plus_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

<<<<<<< HEAD
  
=======
  assets:
    - assets/images/
    

>>>>>>> 9ba214774477ed6ce2a74a034eb30fc3e0da156c
  fonts:
    - family: Syne
      fonts:
        - asset: assets/fonts/Syne-Regular.ttf
          weight: 400
        - asset: assets/fonts/Syne-Medium.ttf
          weight: 500
        - asset: assets/fonts/Syne-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Syne-Bold.ttf
          weight: 700
        - asset: assets/fonts/Syne-ExtraBold.ttf
          weight: 800

  
  assets:
    - assets/images/doctorBrahimi.png
    - assets/images/doctorSirine.png
    - assets/images/doctorLamis.png
    - assets/images/doctorAbdelillah.png
