name: afia_plus_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_svg: ^2.2.1
  get_it: ^9.2.0
  intl: ^0.20.2
  lucide_flutter: ^0.552.0
  path: ^1.9.1
  shared_preferences: ^2.5.3
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Syne
      fonts:
        - asset: assets/fonts/Syne-Regular.ttf
          weight: 400
        - asset: assets/fonts/Syne-Medium.ttf
          weight: 500
        - asset: assets/fonts/Syne-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Syne-Bold.ttf
          weight: 700
        - asset: assets/fonts/Syne-ExtraBold.ttf
          weight: 800
