name: afia_plus_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.1
  intl: ^0.20.2
  lucide_flutter: ^0.552.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  
<<<<<<< HEAD
=======
=======
>>>>>>> ad7dcdfa4eb5a6bdf65c92dc2557e72a8ac56d1d

>>>>>>> ff6306dba659cd30e1cb89b07d6cab3015026860
  assets:
    - assets/images/
    

<<<<<<< HEAD
=======
<<<<<<< HEAD

=======
>>>>>>> ad7dcdfa4eb5a6bdf65c92dc2557e72a8ac56d1d
>>>>>>> ff6306dba659cd30e1cb89b07d6cab3015026860
  fonts:
    - family: Syne
      fonts:
        - asset: assets/fonts/Syne-Regular.ttf
          weight: 400
        - asset: assets/fonts/Syne-Medium.ttf
          weight: 500
        - asset: assets/fonts/Syne-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Syne-Bold.ttf
          weight: 700
        - asset: assets/fonts/Syne-ExtraBold.ttf
          weight: 800

<<<<<<< HEAD
          
=======
<<<<<<< HEAD
  
=======
>>>>>>> ad7dcdfa4eb5a6bdf65c92dc2557e72a8ac56d1d
>>>>>>> ff6306dba659cd30e1cb89b07d6cab3015026860
