name: afia_plus_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

<<<<<<< HEAD
  
=======
>>>>>>> ad7dcdfa4eb5a6bdf65c92dc2557e72a8ac56d1d

  assets:
    - assets/images/
    

<<<<<<< HEAD

=======
>>>>>>> ad7dcdfa4eb5a6bdf65c92dc2557e72a8ac56d1d
  fonts:
    - family: Syne
      fonts:
        - asset: assets/fonts/Syne-Regular.ttf
          weight: 400
        - asset: assets/fonts/Syne-Medium.ttf
          weight: 500
        - asset: assets/fonts/Syne-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Syne-Bold.ttf
          weight: 700
        - asset: assets/fonts/Syne-ExtraBold.ttf
          weight: 800

<<<<<<< HEAD
  
=======
>>>>>>> ad7dcdfa4eb5a6bdf65c92dc2557e72a8ac56d1d
